candidates={}
candidates['romney']='MittRomney mittromney romney mitt ROMNEY'.split()
candidates['ronpaul']='RonPaul ronpaul ron paul PAUL'.split()
#candidates['bachman']='MicheleBachmann michelebachmann michiele bachman'.split()
candidates['perry']='GovernorPerry governorperry rickperry rick perry PERRY'.split()
candidates['gingrich']='NewtGingrich newtgingrich newt gingrich GINGRICH'.split()
#candidates['obama']='BarackObama barackobama barack obama potus president'.split()
candidates['santorum']='RickSantorum ricksantorum santorum SANTORUM'
candidates['huntsman']='Jon2012HQ JonHuntsman huntsman HUNTSMAN'.split()